version: '2'
services:
  jenkins_container:
    build:
      context: "./docker_jenkins"
    ports:
      - 8080:8080
  vault_container:
    build:
      context: "./vault"
    command: "server"
    ports:
      - 8200:8200
    environment:
      - VAULT_ADDR=http://0.0.0.0:8200
      - 'VAULT_LOCAL_CONFIG={"backend": {"inmem": {}}, "listener": {"tcp": {"address": "0.0.0.0:8200", "tls_disable": "1"}}, "disable_mlock": true}'
      - SKIP_SETCAP=true
